In [14]:
import sys
import pandas as pd
from pathlib import Path

# Caminho real do notebook 
NOTEBOOK_DIR = Path.cwd() 

# Sobe até a raiz do projeto (shopnow/) 
ROOT = NOTEBOOK_DIR.parents[2] 

# Adiciona ao sys.path 
if str(ROOT) not in sys.path: sys.path.append(str(ROOT))
from pipeline.extract import carregar_dados_csv

In [22]:
df_atendimento = carregar_dados_csv()["atendimento"]

→ Carregando: atendimento_raw.csv
→ Carregando: clientes_raw.csv
→ Carregando: compras_raw.csv
→ Carregando: estoque_raw.csv
→ Carregando: financeiro_raw.csv
→ Carregando: fornecedores_raw.csv
→ Carregando: logistica_raw.csv
→ Carregando: marketing_campanhas_raw.csv
→ Carregando: marketing_performance_raw.csv
→ Carregando: produtos_raw.csv
→ Carregando: rh_raw.csv
→ Carregando: vendas_raw.csv

In [31]:
df_atendimento
#df_atendimento.query("canal == 'site'")

,id_atendimento,id_pedido,id_cliente,id_agente,canal,motivo_principal,submotivo,area_responsavel,prioridade,complexidade,...,tempo_agente_minutos,custo_hora_agente,custo_atendimento,valor_compensacao,valor_estornado,nota_satisfacao,nps_classificacao,houve_reclamacao_publica,cliente_churnou_apos_atendimento,houve_recompra_30_dias
0,1,ped-36062,NaN,38,app,Entrega,Erro na cobrança,Tecnologia,Crítica,Média,...,36,31.16,371.63,-20,0,0,Promotor,Sim,Sim,Não
1,646,ped-91070,1183.0,46,site,Entrega,erro cobrança,Financeiro,baixa,baixa,...,18,50.39,15.12,50,-100,3,detrator,Não,Sim,nao
2,3787,PED-45382,NaN,50,Site,pagamento,Atraso,Financeiro,Crítica,Média,...,-10,33.01,-5.50,50,0,6,promotor,nao,Não,Não
3,4781,PED-57447,NaN,6,Site,entrega,Erro na cobrança,Tecnologia,Média,Alta,...,-10,90.77,-15.13,0,200,2,detrator,nao,sim,nao
4,2405,PED-30730,NaN,33,SITE,Cancelamento,atraso,Tecnologia,Alta,alta,...,-10,97.69,-16.28,0,0,0,NaN,NAO,sim,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,ped-43457,828.0,5,site,Troca,Atraso,Financeiro,Crítica,alta,...,52,61.62,53.40,100,0,0,detrator,Não,Sim,Sim
9996,4624,PED-66483,NaN,12,chat online,Entrega,Atraso,logistica,Baixa,baixa,...,-10,97.89,475.85,100,0,6,NaN,SIM,nao,Não
9997,3426,PED-93582,726.0,7,Telefone,pagamento,Arrependimento,Comercial,Média,Alta,...,114,99.34,323.42,0,200,3,detrator,Sim,Sim,Não
9998,4589,ped-78260,133.0,49,site,Entrega,erro cobrança,Comercial,Baixa,baixa,...,-10,71.16,-11.86,100,0,0,promotor,nao,sim,Não
9999,10000,ped-47926,101.0,41,Site,Pagamento,Produto errado,logistica,Alta,Alta,...,-10,69.65,-11.61,100,0,4,Neutro,Sim,sim,nao

In [34]:
# Use o map para percorrer cada célula do DataFrame
# Converte todos os elementos do DataFrame para minúsculo
# O lambda garante que apenas strings sejam processadas (evita erros com números ou nulos)

df_atendimento = df_atendimento.map(lambda x: x.lower() if isinstance(x, str) else x)
df_atendimento

,id_atendimento,id_pedido,id_cliente,id_agente,canal,motivo_principal,submotivo,area_responsavel,prioridade,complexidade,...,tempo_agente_minutos,custo_hora_agente,custo_atendimento,valor_compensacao,valor_estornado,nota_satisfacao,nps_classificacao,houve_reclamacao_publica,cliente_churnou_apos_atendimento,houve_recompra_30_dias
0,1,ped-36062,NaN,38,app,entrega,erro na cobrança,tecnologia,crítica,média,...,36,31.16,371.63,-20,0,0,promotor,sim,sim,não
1,646,ped-91070,1183.0,46,site,entrega,erro cobrança,financeiro,baixa,baixa,...,18,50.39,15.12,50,-100,3,detrator,não,sim,nao
2,3787,ped-45382,NaN,50,site,pagamento,atraso,financeiro,crítica,média,...,-10,33.01,-5.50,50,0,6,promotor,nao,não,não
3,4781,ped-57447,NaN,6,site,entrega,erro na cobrança,tecnologia,média,alta,...,-10,90.77,-15.13,0,200,2,detrator,nao,sim,nao
4,2405,ped-30730,NaN,33,site,cancelamento,atraso,tecnologia,alta,alta,...,-10,97.69,-16.28,0,0,0,NaN,nao,sim,sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,ped-43457,828.0,5,site,troca,atraso,financeiro,crítica,alta,...,52,61.62,53.40,100,0,0,detrator,não,sim,sim
9996,4624,ped-66483,NaN,12,chat online,entrega,atraso,logistica,baixa,baixa,...,-10,97.89,475.85,100,0,6,NaN,sim,nao,não
9997,3426,ped-93582,726.0,7,telefone,pagamento,arrependimento,comercial,média,alta,...,114,99.34,323.42,0,200,3,detrator,sim,sim,não
9998,4589,ped-78260,133.0,49,site,entrega,erro cobrança,comercial,baixa,baixa,...,-10,71.16,-11.86,100,0,0,promotor,nao,sim,não
9999,10000,ped-47926,101.0,41,site,pagamento,produto errado,logistica,alta,alta,...,-10,69.65,-11.61,100,0,4,neutro,sim,sim,nao